### ISSUE TITLE
ansi-regex - violations (TrustSource generated task)

### ISSUE THREAD

**Issue by jthDEV** [TrustSource/ts-node-client#20]
Component "ansi-regex" has status "violations" 
This is due to Viability problems; Vulnerability problems; License warnings. 
Please check the need for this component and resolve this violations. 
The component is found at: /npm:6.14.17/cli-columns:3.1.2/strip-ansi:3.0.1/ansi-regex:2.1.1; /npm:6.14.17/cli-columns:3.1.2/string-width:2.1.1/strip-ansi:4.0.0/ansi-regex:3.0.0; /npm:6.14.17/libnpx:10.2.4/yargs:14.2.3/string-width:3.1.0/strip-ansi:5.2.0/ansi-regex:4.1.0; /npm:6.14.17/libnpx:10.2.4/yargs:14.2.3/cliui:5.0.0/strip-ansi:5.2.0/ansi-regex:4.1.1,/npm:6.14.17/libnpx:10.2.4/yargs:14.2.3/cliui:5.0.0/wrap-ansi:5.1.0/strip-ansi:5.2.0/ansi-regex:4.1.1; /yargs:17.5.0/cliui:7.0.4/strip-ansi:6.0.1/ansi-regex:5.0.1. 

PLEASE NOTE: starting from 5.0.1. issues are fixed.
Thank you for your support.

**Comment by olexandrbig** [comment]
resolved
