### ISSUE TITLE
dependencies from package-lock.json not handled properly

### ISSUE THREAD

**Issue by drallgood** [TrustSource/ts-node-client#22]
I discovered that dependencies from package-lock.json seem to be ignored now. It worked fine a few months ago (not sure when the change was introduced) but now all you get as a result is the own package.

Reason is here:
https://github.com/TrustSource/ts-node-client/blob/9e425f93d32ae57d28055c330fe79d6bcef2ffb4/lib/npm-scanner.js#L170

This function is also called for the package-lock.json file but `npmDependency.dependencies` obviously doesn't exist at the root of the file.

**Comment by drallgood** [comment]
Thanks @olexandrbig 

I already debugged the code and the lock-file is available. It's v3 (as provided by node 18 LTS), so that's probably why

**Comment by olexandrbig** [comment]
Will be resolved in release 3.2.0
